### ISSUE TITLE
set up python env

### ISSUE THREAD

**Issue by jacobian** [jacobian/windows#7]
- [x] biggest question: do i want to do this as part of ubuntu for windows, or as a native windows thing?
- [x] install python
- [x] pip, virtualenv
- [ ] virtualenvwrapper 
- [ ] pipsi
- [ ] ipython + notebook

**Comment by jacobian** [comment]
Some help in IRC points towards probably wanting the MSI version.

```
7:54 AM <jacobkm> Any Windows users in the house? I'm trying to decide if I should install Python via the Ubuntu for Windows thing, or the native MSI.
7:54 AM <jacobkm> I'm more or less completely new to Windows so the Linux-y option seems compelling, but I also wonder if I'd be setting myself up for failure in the future.
7:56 AM <haikuginger> Unless you're developing specifically for Windows, I would probably use the WSL version. Less likely to run into odd issues, especially with anything that depends on C libraries
7:56 AM <haikuginger> if you ARE developing something that's going to run on Windows, then I'd develop on the Windows-native version so that you can have a better idea of the complications that might happen during a deploy.
7:57 AM <jacobkm> I somewhat doubt I'll be doing any native Windows stuff - I plan to use this thing mostly like I use my Mac, i.e. as a slightly weird Unix with good hardware :)
7:59 AM <haikuginger> then I would probably use WSL. :)
7:59 AM <dstufft> jacobkm: are you switching your primary desktop to Windows?
7:59 AM <nedbat> jacobkm: why not install linux on it then?
8:00 AM <jacobkm> dstufft: I'm giving it a try yes (for my personal machine, still using a Mac for work)
8:00 AM <haikuginger> note that it's not recommended for you to modify Linux files with Windows applications, so you'd need to either 1) do all your editing in the shell or 2) do some nasty hacks to run an X server on Windows to show Linux GUI applications (https://www.slightfuture.com/how-to/x-on-wsl)
8:01 AM <jacobkm> nedbat: I find Linux desktop environments even harder to use than Windows, and most of the motiviation was about the specific hardware (Surface) which has pretty poor Linux support last I checked.
8:01 AM <jacobkm> haikuginger: erk that's not great, even text files? I'd planned on continuing to use Sublime.
8:01 AM <dstufft> jacobkm: I've been kind of thinking about it lately., well where "it" == leaving Apple computers. Mostly because Apple seems to neglating their desktops
8:02 AM <haikuginger> different permissions systems. https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/
8:02 AM <jacobkm> dstufft: welp, I'm keeping notes at github.com/jacobian/windows, if you want to follow along with my experiment :)
8:02 AM <nedbat> jacobkm: I was windows-native until about four years ago, but that means i stopped at windows 7.
8:03 AM <jacobkm> dstufft: the surface hardware is delightful, easily the niftiest computer-y thing I've bought in ages. It remains to be seen if I can re-train 30 years of Mac muscle memory to be OK with windows, though
8:04 AM <jacobkm> haikuginger: hm that points towards wanting the native Python, then. Not sure I want to make switching back to Vim part of this experiment :)
```

**Comment by jacobian** [comment]
After some hilarity figuring out which of the six Python installers I want, I picked one (64-bit, downloadable installer), ran it, and it Just Worked. NB the "add to PATH" option isn't checked by default (I turned that on), and it wants to install IDLE (I turned that off). But otherwise the defaults seem great, and I have a working python and pip with almost no effort.

**Comment by jacobian** [comment]
virtualenv works, virtualenvwrapper is bash-only, but https://pypi.python.org/pypi/virtualenvwrapper-win appears to be a thing, going to try that.

**Comment by jacobian** [comment]
NB from dstufft: `pip install -U pip` doesn't really work because it can't overwrite `pip.exe`. `python -m pip install -U pip` is the correct incantation.

**Comment by jacobian** [comment]
Oh: 

> However, they only work in the regular command prompt. They will not work in Powershell. There are other virtualenvwrapper projects out there for Powershell.

Guess I need to find one of those other things, then.

**Comment by jacobian** [comment]
https://pypi.python.org/pypi/virtualenvwrapper-powershell/2.7.1 perhaps?

**Comment by jacobian** [comment]
Nope, that fails with a SyntaxError on install:

```
PS C:\Users\jacob\c> pip install virtualenvwrapper-powershell
Collecting virtualenvwrapper-powershell
  Downloading virtualenvwrapper-powershell-12.7.8.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\jacob\AppData\Local\Temp\pip-build-_5fksvmg\virtualenvwrapper-powershell\setup.py", line 76
        TOKEN_READ = 0x00020000L | 0x0008
                               ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\jacob\AppData\Local\Temp\pip-build-_5fksvmg\virt
ualenvwrapper-powershell\
```

**Comment by jacobian** [comment]
On further reading: it really looks like using a Linux-Python should be fine, as long as I keep my shared files (stuff I want to edit in Windows apps too) under `/mnt/c` rather than in Linux-`~`: https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/. Some early tests seem to confirm this: I can use Linux-git to clone a repo in `/mnt/c/Users/jacob`, edit it from Windows-Sublime, and then run it in Linux-Python. This seems like a better world to me, maybe I should go that direction.

**Comment by jacobian** [comment]
The Linux Python setup:

```
sudo apt install build-essential libssl-dev libreadline-dev libsqlite3-dev libzip2
curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
pyenv install 3.5.2
```

and so forth - it's really just a linux. Almost positive this is better than the windows way, at least for me
